name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - Testing_Server
trigger:
  branches:
    include:
      - Testing_Server

variables:
  VITE_API_URL: "https://d101.qsronline.com/QSROnlineGateway/"

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-happy-river-0fb1ef810-variable-group
  steps:
  - checkout: self
    submodules: true
    
  - script: |
      cd nextgen-frontend
      echo "##vso[task.setvariable variable=VITE_API_URL]$(VITE_API_URL)"
      npm install
      npm run build
    displayName: 'Build application'

  - task: CopyFiles@2
    displayName: 'Copy staticwebapp.config.json to dist folder'
    inputs:
     SourceFolder: nextgen-frontend
     Contents: 'staticwebapp.config.json'
     TargetFolder: 'nextgen-frontend/dist'
    
  - task : PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'nextgen-frontend/dist'
      ArtifactName: 'drop'

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_RIVER_0FB1EF810)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "/nextgen-frontend" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "dist" # Built app content directory - optional
###### End of Repository/Build Configurations ######

